name: Suggestion
description: Write a suggestion
title: "[Suggestion]: "
labels: ["Suggestion"]
body:
  - type: input
    id: name
    attributes:
      label: Your Name
      description: How can we address you?
  - type: textarea
    id: suggestion
    attributes:
      label: What is your suggestion?
      description: Do you want something added/changed?
    validations:
      required: true
  - type: markdown
    id: discord
    attributes:
      value: Join our [Discord](https://discord.gg/TfUuCBmU2x) for more information and daily updates!
